#!/usr/bin/env python3
# =============================================================================
#  aggregate_overhead.py
#
#  Reads the CSV produced by run_miplib_benchmark.py and emits the three
#  LaTeX tables that the paper marks \todo{} pending the cluster sweep:
#
#    (1) data_table_full_effect.tex      (main paper, Table~\ref{tab:scip-reductions})
#        per-instance reduction counts in the three integration modes.
#
#    (2) data_table_overhead_summary.tex (main paper, Table~\ref{tab:scip-effect})
#        paired-seed geometric-mean ratios t_cfg / t_baseline plus median
#        plug-in overhead, stratified by ALL / REDUCTIONS / NO_REDUCTIONS.
#
#    (3) data_table_overhead_per_instance.tex (online supplement EC.8)
#        per-instance overhead row for every instance in the sweep.
#
#  Five-config harness (run_miplib_benchmark.py CONFIGS):
#    baseline_presolve_off          (SCIP_PARAMSETTING_OFF, no plug-in)
#    ours_pure_standalone           (SCIP_PARAMSETTING_OFF + plug-in; agg auto-skip)
#    ours_cooperative_standalone    (per-presolver OFF + plug-in; agg works)
#    baseline_presolve_on           (SCIP+PaPILO default, no plug-in)
#    ours_on_top                    (SCIP+PaPILO default + plug-in)
#
#  Usage:
#      python3 aggregate_overhead.py results/run_30/results.csv \
#          --out-per-instance ../../paper/data_table_overhead_per_instance.tex \
#          --out-summary      ../../paper/data_table_overhead_summary.tex \
#          --out-reductions   ../../paper/data_table_full_effect.tex
# =============================================================================

from __future__ import annotations

import argparse
import csv
import math
import statistics
import sys
from collections import defaultdict
from pathlib import Path


# ----- Statistics helpers ----------------------------------------------------

def geo_mean(xs):
    xs = [x for x in xs if x is not None and x > 0]
    if not xs:
        return None
    return math.exp(sum(math.log(x) for x in xs) / len(xs))


def median(xs):
    xs = [x for x in xs if x is not None]
    if not xs:
        return None
    return statistics.median(xs)


# ----- CSV loading -----------------------------------------------------------

def load_csv(path: Path):
    with path.open() as f:
        return list(csv.DictReader(f))


# ----- Per-instance reduction table (Table 1) -------------------------------

def reductions_per_instance(rows):
    """Returns one dict per instance with reduction counts in each of the
    three plug-in modes (taking the max across seeds to be robust to
    seed-to-seed variation in apply timing)."""
    by_inst = defaultdict(lambda: defaultdict(list))
    for r in rows:
        by_inst[r["instance"]][r["config"]].append(r)

    out = []
    for inst, cfgs in sorted(by_inst.items()):
        def sum_red(cfg):
            cfg_rows = cfgs.get(cfg, [])
            if not cfg_rows:
                return (None, None, None, None)
            # Take max across seeds so seed-to-seed apply variation doesn't
            # underreport the true reduction set.
            de = max(int(r["plugin_de"]) for r in cfg_rows)
            ie = max(int(r["plugin_ie"]) for r in cfg_rows)
            f0 = max(int(r["plugin_f0"]) for r in cfg_rows)
            f1 = max(int(r["plugin_f1"]) for r in cfg_rows)
            return (de, ie, f0, f1)

        pure = sum_red("ours_pure_standalone")
        coop = sum_red("ours_cooperative_standalone")
        ontop = sum_red("ours_on_top")
        out.append({
            "instance": inst,
            "pure": pure, "coop": coop, "ontop": ontop,
            "any_red": any(any(x and x > 0 for x in t if x is not None)
                           for t in (pure, coop, ontop)),
        })
    return out


def emit_reductions_tex(table, out_path: Path):
    def cell(quad):
        if quad == (None, None, None, None):
            return r"\multicolumn{4}{c}{--}"
        de, ie, f0, f1 = quad
        return f"{de} & {ie} & {f0} & {f1}"

    with out_path.open("w") as f:
        f.write("% Auto-generated by aggregate_overhead.py; do not hand-edit.\n")
        f.write("\\small\n")
        f.write("\\setlength{\\tabcolsep}{3pt}\n")
        f.write("\\begin{tabular}{l|rrrr|rrrr|rrrr}\n\\hline\n")
        f.write("Instance & \\multicolumn{4}{c|}{Pure standalone} & "
                "\\multicolumn{4}{c|}{Cooperative} & "
                "\\multicolumn{4}{c}{On-top of PaPILO} \\\\\n")
        f.write("         & DE & IE & $F_0$ & $F_1$ "
                "& DE & IE & $F_0$ & $F_1$ "
                "& DE & IE & $F_0$ & $F_1$ \\\\\n\\hline\n")
        rows_with_redux = [r for r in table if r["any_red"]]
        rows_without    = [r for r in table if not r["any_red"]]
        for r in rows_with_redux:
            f.write(f"\\texttt{{{r['instance'].replace('_', r'\_')}}} & "
                    f"{cell(r['pure'])} & {cell(r['coop'])} & {cell(r['ontop'])} "
                    f"\\\\\n")
        if rows_without:
            f.write("\\hline\n")
            f.write(f"\\multicolumn{{13}}{{l}}{{\\textit{{{len(rows_without)} "
                    "additional instances: all reduction counts $= 0$ in all "
                    "three modes (see online supplement EC.8).}} \\\\\n")
        f.write("\\hline\n\\end{tabular}\n")


# ----- Geomean summary table (Table 2) --------------------------------------

def per_instance_solve_summary(rows):
    """Returns one dict per instance with median solve times per config and
    median plug-in overhead.  Used by both the summary table and the
    per-instance overhead table."""
    by_inst = defaultdict(lambda: defaultdict(list))
    for r in rows:
        by_inst[r["instance"]][r["config"]].append(r)

    out = []
    for inst, cfgs in sorted(by_inst.items()):
        def med_solve(cfg):
            xs = [float(r["solve_s"]) for r in cfgs.get(cfg, [])
                  if r["solve_s"] and r["status"] in ("OPT", "TL")]
            return median(xs)

        def med_overhead(cfg):
            xs = [float(r["plugin_total_s"]) for r in cfgs.get(cfg, [])
                  if r["plugin_total_s"]]
            return median(xs)

        def max_reductions(cfg):
            cfg_rows = cfgs.get(cfg, [])
            if not cfg_rows:
                return 0
            return max(int(r["plugin_de"]) + int(r["plugin_ie"]) +
                       int(r["plugin_f0"]) + int(r["plugin_f1"])
                       for r in cfg_rows)

        b_off    = med_solve("baseline_presolve_off")
        pure     = med_solve("ours_pure_standalone")
        coop     = med_solve("ours_cooperative_standalone")
        b_on     = med_solve("baseline_presolve_on")
        ontop    = med_solve("ours_on_top")

        ovh_pure = med_overhead("ours_pure_standalone")
        ovh_coop = med_overhead("ours_cooperative_standalone")
        ovh_top  = med_overhead("ours_on_top")

        nred_any = max(max_reductions(c) for c in
                       ("ours_pure_standalone",
                        "ours_cooperative_standalone",
                        "ours_on_top"))

        def safe_ratio(num, den):
            if num is None or den is None or den <= 0:
                return None
            return num / den

        out.append({
            "instance":   inst,
            "b_off":      b_off,
            "pure":       pure,
            "coop":       coop,
            "b_on":       b_on,
            "ontop":      ontop,
            "ovh_pure":   ovh_pure,
            "ovh_coop":   ovh_coop,
            "ovh_top":    ovh_top,
            "r_pure":     safe_ratio(pure,  b_off),
            "r_coop":     safe_ratio(coop,  b_off),
            "r_ontop":    safe_ratio(ontop, b_on),
            "n_reductions": nred_any,
        })
    return out


def emit_summary_tex(table, out_path: Path):
    strata = {
        "ALL":           table,
        "Reductions":    [r for r in table if r["n_reductions"] > 0],
        "No reductions": [r for r in table if r["n_reductions"] == 0],
    }

    def fm(x, p=3):
        return "--" if x is None else f"{x:.{p}f}"

    with out_path.open("w") as f:
        f.write("% Auto-generated by aggregate_overhead.py; do not hand-edit.\n")
        f.write("\\small\n")
        f.write("\\setlength{\\tabcolsep}{6pt}\n")
        f.write("\\begin{tabular}{l|r|rrr|r|r}\n")
        f.write("Stratum & \\#inst.\\ & "
                "$\\overline{\\rm Pure}$ & "
                "$\\overline{\\rm Coop.}$ & "
                "$\\overline{\\rm On\\text{-}top}$ & "
                "med.\\ plug-in (s) & med.\\ plug-in / solve (\\%) "
                "\\\\\n\\hline\n")
        for label, sub in strata.items():
            gm_pure  = geo_mean([r["r_pure"]  for r in sub])
            gm_coop  = geo_mean([r["r_coop"]  for r in sub])
            gm_ontop = geo_mean([r["r_ontop"] for r in sub])
            med_ovh  = median([r["ovh_top"] for r in sub])
            pct = []
            for r in sub:
                if (r["ovh_top"] is not None and
                    r["b_on"] is not None and r["b_on"] > 0):
                    pct.append(100.0 * r["ovh_top"] / r["b_on"])
            med_pct = median(pct)
            f.write(f"\\textsc{{{label}}} & {len(sub):>4d} & "
                    f"{fm(gm_pure)} & {fm(gm_coop)} & {fm(gm_ontop)} & "
                    f"{fm(med_ovh, 3)} & {fm(med_pct, 2)} \\\\\n")
        f.write("\\hline\n\\end{tabular}\n")


# ----- Per-instance overhead table (Table 3) --------------------------------

def emit_per_instance_tex(table, out_path: Path):
    def fmt(x, w=8, p=2):
        return ("--" if x is None else f"{x:>{w}.{p}f}")

    with out_path.open("w") as f:
        f.write("% Auto-generated by aggregate_overhead.py; do not hand-edit.\n")
        f.write("\\small\n")
        f.write("\\setlength{\\tabcolsep}{4pt}\n")
        f.write("\\begin{tabular}{l|r|rrrrr|r|r}\n\\hline\n")
        f.write("Instance & \\#red.\\ & "
                "$t_{\\rm base,off}$ & $t_{\\rm pure}$ & $t_{\\rm coop}$ & "
                "$t_{\\rm base,on}$ & $t_{\\rm on\\text{-}top}$ & "
                "plug-in (s) & ratio$_{\\rm on}$ \\\\\n\\hline\n")
        for r in table:
            ratio_on = (r["ontop"] / r["b_on"]) if (r["b_on"] and r["ontop"]
                       and r["b_on"] > 0) else None
            f.write(
                f"\\texttt{{{r['instance'].replace('_', r'\_')}}} & "
                f"{r['n_reductions']:>4d} & "
                f"{fmt(r['b_off'])} & {fmt(r['pure'])} & {fmt(r['coop'])} & "
                f"{fmt(r['b_on'])} & {fmt(r['ontop'])} & "
                f"{fmt(r['ovh_top'], 6, 3)} & {fmt(ratio_on, 6, 3)} \\\\\n")
        f.write("\\hline\n\\end{tabular}\n")


# ----- Driver ---------------------------------------------------------------

def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("csv", type=Path, help="results CSV from run_miplib_benchmark.py")
    ap.add_argument("--out-per-instance", required=True, type=Path,
                    help="path for the per-instance overhead .tex (online supplement EC.8)")
    ap.add_argument("--out-summary",      required=True, type=Path,
                    help="path for the stratified summary .tex (Table~\\ref{tab:scip-effect})")
    ap.add_argument("--out-reductions",   required=True, type=Path,
                    help="path for the per-instance reduction-counts .tex "
                         "(Table~\\ref{tab:scip-reductions})")
    args = ap.parse_args()
    if not args.csv.exists():
        sys.exit(f"not found: {args.csv}")
    rows = load_csv(args.csv)
    print(f"[aggregate] loaded {len(rows)} rows from {args.csv}")

    reds = reductions_per_instance(rows)
    summ = per_instance_solve_summary(rows)

    for p in (args.out_per_instance, args.out_summary, args.out_reductions):
        p.parent.mkdir(parents=True, exist_ok=True)

    emit_reductions_tex(reds, args.out_reductions)
    emit_summary_tex(summ,    args.out_summary)
    emit_per_instance_tex(summ, args.out_per_instance)

    print(f"[aggregate] wrote:")
    print(f"  {args.out_reductions}    (Table tab:scip-reductions, Section 6.5)")
    print(f"  {args.out_summary}       (Table tab:scip-effect,    Section 6.5)")
    print(f"  {args.out_per_instance}  (Appendix EC.8, online supplement)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
