#!/usr/bin/env python3
# =============================================================================
#  build_conflict_graph.py
#
#  Build the CBC conflict graph for an MPS/LP instance and dump it as a
#  literal-arc text file that the SCIP implgraph plug-in (and the standalone
#  arc-list runner) can consume directly.
#
#  Why Python and not C++?  Ubuntu's coinor-libcbc-dev package does not ship
#  the CoinConflictGraph.hpp header that exposes CBC's internal conflict-graph
#  builder, so we cannot call it from C++ without compiling CBC from source.
#  python-mip wraps the same internal builder via cffi, which gives us full
#  access in a few lines of Python.  We then hand the result to the C++
#  plug-in through a tiny text file -- one line per arc -- and let the
#  performance-critical SCC + reachability pipeline run in C++ as designed.
#
#  Output format (compatible with standalone_runner and the plug-in's
#  arcsfile loader):
#
#      # optional comment lines start with '#'
#      <bit><varname>   <bit><varname>          # one arc per line
#
#  where <bit> is '0' or '1'.  Variable names are exactly as in the source
#  MPS file (no transformation prefix).
#
#  Algorithm: for each binary variable v and each value a in {0, 1}, query
#  ConflictGraph.conflicting_assignments((v == a)) which returns
#  (vars_at_one, vars_at_zero) -- the lists of variables whose assignment
#  to 1 (resp. 0) conflicts with (v = a).  We translate each conflict
#  (v=a) ^ (w=b)  ==>  (v=a) -> (w = 1-b).  CBC's conflict graph is
#  symmetric, so the contrapositive arc is emitted automatically when we
#  query (w == b).
#
#  Self-conflicts -- the trivial pairs (v=a) ^ (v=1-a) which every variable
#  has -- are filtered out: they would produce a self-loop arc, harmless
#  for the SCC pipeline but noisy in the output file.
#
#  Usage:
#      python3 build_conflict_graph.py [--verbose] [--cache]
#                                       input.mps  output.arcs
#
#  With --cache, if output.arcs already exists and is newer than the input
#  MPS, the script is a no-op and exits 0.  This is what the benchmark
#  harness uses to amortise the cost across the five paired seeds.
# =============================================================================

from __future__ import annotations

import argparse
import os
import sys
import time
from pathlib import Path


def emit_arcs(
    mps_path: Path,
    out_path: Path,
    verbose: bool = False,
) -> tuple[int, int]:
    """Build the CBC conflict graph and write the arc file.

    Returns (n_binaries, n_arcs).
    """
    # Imported lazily so that --cache hits don't pay for the cbcbox import.
    import mip

    t0 = time.time()
    m = mip.Model(solver_name="CBC")
    m.verbose = 0
    m.read(str(mps_path))
    t_read = time.time() - t0

    binaries = [v for v in m.vars if v.var_type == mip.BINARY]
    bin_names = {v.name for v in binaries}

    if verbose:
        sys.stderr.write(
            f"[build_conflict_graph] read {mps_path.name} in {t_read:.2f}s: "
            f"{m.num_cols} cols ({len(binaries)} binary), {m.num_rows} rows\n"
        )

    if not binaries:
        with out_path.open("w") as fh:
            fh.write(f"# no binary variables in {mps_path.name}\n")
        return (0, 0)

    t1 = time.time()
    cg = mip.ConflictGraph(m)
    t_cg = time.time() - t1
    if verbose:
        sys.stderr.write(
            f"[build_conflict_graph] CBC ConflictGraph built in {t_cg:.2f}s, "
            f"density={cg.density:.3e}\n"
        )

    t2 = time.time()
    n_arcs = 0
    with out_path.open("w") as fh:
        fh.write(f"# conflict graph for {mps_path.name}\n")
        fh.write(
            f"# generated by build_conflict_graph.py "
            f"at {time.strftime('%Y-%m-%d %H:%M:%S')}\n"
        )
        fh.write(f"# {len(binaries)} binaries, {m.num_rows} rows, "
                 f"density={cg.density:.3e}\n")
        for v in binaries:
            vname = v.name
            # ---- Query (v = 1) ----------------------------------------------
            #
            # conflicting_assignments returns (vars_at_one, vars_at_zero):
            #   vars_at_one[i]  : (v=1) ^ (vars_at_one[i] = 1) is infeasible
            #     => arc (v=1) -> (vars_at_one[i] = 0)
            #   vars_at_zero[i] : (v=1) ^ (vars_at_zero[i] = 0) is infeasible
            #     => arc (v=1) -> (vars_at_zero[i] = 1)
            try:
                one_conf, zero_conf = cg.conflicting_assignments(v)
            except Exception as exc:  # pragma: no cover -- defensive
                sys.stderr.write(
                    f"[build_conflict_graph] WARNING: "
                    f"conflicting_assignments({vname}=1) failed: {exc}\n"
                )
                one_conf, zero_conf = [], []
            for w in one_conf:
                if w.name == vname:        # trivial self-conflict
                    continue
                if w.name not in bin_names:
                    continue
                fh.write(f"1{vname} 0{w.name}\n")
                n_arcs += 1
            for w in zero_conf:
                if w.name == vname:
                    continue
                if w.name not in bin_names:
                    continue
                fh.write(f"1{vname} 1{w.name}\n")
                n_arcs += 1

            # ---- Query (v = 0) ----------------------------------------------
            #
            # The LinExpr  (v == 0)  selects the complement literal.
            try:
                one_conf, zero_conf = cg.conflicting_assignments(v == 0)
            except Exception as exc:  # pragma: no cover -- defensive
                sys.stderr.write(
                    f"[build_conflict_graph] WARNING: "
                    f"conflicting_assignments({vname}=0) failed: {exc}\n"
                )
                one_conf, zero_conf = [], []
            for w in one_conf:
                if w.name == vname:
                    continue
                if w.name not in bin_names:
                    continue
                fh.write(f"0{vname} 0{w.name}\n")
                n_arcs += 1
            for w in zero_conf:
                if w.name == vname:
                    continue
                if w.name not in bin_names:
                    continue
                fh.write(f"0{vname} 1{w.name}\n")
                n_arcs += 1

    t_dump = time.time() - t2

    if verbose:
        sys.stderr.write(
            f"[build_conflict_graph] wrote {n_arcs} arcs to {out_path} "
            f"in {t_dump:.2f}s\n"
        )
        sys.stderr.write(
            f"[build_conflict_graph] total {time.time() - t0:.2f}s\n"
        )

    return (len(binaries), n_arcs)


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("input", type=Path, help="MPS or LP file to read")
    parser.add_argument("output", type=Path, help="arcs file to write")
    parser.add_argument(
        "--cache",
        action="store_true",
        help="skip if output exists and is newer than input",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="log timings to stderr",
    )
    args = parser.parse_args()

    if not args.input.is_file():
        sys.stderr.write(f"error: {args.input}: not found\n")
        return 2

    if args.cache and args.output.is_file():
        if args.output.stat().st_mtime >= args.input.stat().st_mtime:
            if args.verbose:
                sys.stderr.write(
                    f"[build_conflict_graph] cache hit: {args.output} is newer "
                    f"than {args.input}\n"
                )
            return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)

    try:
        n_bin, n_arcs = emit_arcs(args.input, args.output, verbose=args.verbose)
    except Exception as exc:
        sys.stderr.write(f"error: building conflict graph failed: {exc}\n")
        # Remove any partial output so --cache doesn't think it succeeded.
        try:
            args.output.unlink()
        except FileNotFoundError:
            pass
        return 1

    if args.verbose:
        sys.stderr.write(
            f"[build_conflict_graph] done: {n_bin} binaries -> {n_arcs} arcs\n"
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
